apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defi-copilot-ingress
  namespace: defi-copilot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.defi.vigasin.com
        - api.defi.vigasin.com
      secretName: defi-copilot-tls
  rules:
    - host: app.defi.vigasin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: defi-copilot-web
                port:
                  number: 3000
    - host: api.defi.vigasin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: defi-copilot-api
                port:
                  number: 4000
