apiVersion: v1
kind: ServiceAccount
metadata:
  name: defi-copilot-api
  namespace: defi-copilot
imagePullSecrets:
  - name: registry-defi-copilot-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: defi-copilot-web
  namespace: defi-copilot
imagePullSecrets:
  - name: registry-defi-copilot-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: defi-copilot-worker
  namespace: defi-copilot
imagePullSecrets:
  - name: registry-defi-copilot-registry
