apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defi-copilot-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: defi-copilot

  source:
    repoURL: "https://github.com/ivigasin/defi-copilot.git"
    targetRevision: main
    path: infra/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: defi-copilot-staging

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: defi-copilot-secrets
      jsonPointers:
        - /data

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
